"""add foreign key to onboardin

Revision ID: adc17ca6bbd4
Revises: 8f3c479a228b
Create Date: 2024-06-26 19:43:36.927754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adc17ca6bbd4'
down_revision = '8f3c479a228b'
branch_labels = None
depends_on = None

tmp_onboardings = "tmp_onboardings"
def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        tmp_onboardings,
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('employee_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='fk_onboardings_employee_id_employees')
    )

    # Migrate data from old table to new table
    op.execute(f"INSERT INTO {tmp_onboardings} (id, employee_id) SELECT id, employee_id FROM onboardings")

    # Drop the old table
    op.drop_table('onboardings')

    # Rename the new table to the original table name
    op.rename_table(tmp_onboardings, 'onboardings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        tmp_onboardings,
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('employee_id', sa.Integer(), nullable=True),
    )

    # Migrate data from new table back to old table
    op.execute(f"INSERT INTO {tmp_onboardings} (id, employee_id) SELECT id, employee_id FROM onboardings")

    # Drop the new table
    op.drop_table('onboardings')

    # Rename the temporary table to the original table name
    op.rename_table(tmp_onboardings, 'onboardings')
    # ### end Alembic commands ###
