"""add year

Revision ID: c4f8a35891b4
Revises: 9daf670492ef
Create Date: 2024-06-26 20:06:19.585129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4f8a35891b4'
down_revision = '9daf670492ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'summary')
    op.drop_column('reviews', 'year')
    # ### end Alembic commands ###
